language: go

go:
  - 1.14.x

install: true

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: "Build"
      name: "Build"
      script: go build ./cmd/gitops-cli

    # - stage: "Code Analysis"
    #   before_script:
    #     - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
    #   script: $GOPATH/bin/golangci-lint run ./...

    - stage: "Unit Tests"
      name: "Unit Tests"
      script: go test -v ./...
  