language: go

go:
  - 1.14.x

jobs:
  include:
    - stage: "Build"
      name: "Build"
      script: go build ./cmd/gitops-cli

    - stage: "Code "
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.23.8
      script: golangci-lint run ./...

    - stage: "Unit Tests"
      name: "Unit Tests"
      script: go test -v ./...
  