language: go

go:
  - 1.14.x

before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin v1.23.6

script:
  - go build -v ./...
  - golangci-lint run ./...
  - go test -v ./...
  